name: Vista-ON!Track Customer Implementation
description: A ticket for tracking a customer implementation request for the Vista-ON!Track integration.
title: "Customer Implementation - [Customer Name]"
labels: ["Customer Implementation", "Vista-ON!Track"]
projects: ["ic-tools/1"]

body:
  - type: dropdown
    attributes:
      label: Viewpoint ERP
      description: The Viewpoint ERP that the Customer has in use and wishes to integrate to ON!Track
      multiple: false
      options:
        - Vista
        - Spectrum
      default: 1
    validations:
      required: true
  - type: input
    id: em_company_code
    attributes:
      label: EM Company Code
      description: The CompanyCode of the single EM Company that contains the customers EM Equipment data
      placeholder: "101"
    validations:
      required: false
  - type: input
    id: em_category_id
    attributes:
      label: EM Category ID
      description: The EM Category ID for the category EM Equpiment Location Transfers will be marked
      placeholder: "11"
    validations:
      required: false
  - type: input
    id: em_department_id
    attributes:
      label: EM Department ID
      description: The EM Department ID of the appropriate department for synced EM Equipment Data
      placeholder: "22"
    validations:
      required: false
  - type: textarea
    id: project_company_codes
    attributes:
      label: Project Company Codes
      description: The CompanyCode(s) for the one or more companies that contain JC Jobs that will be synced to ON!Track
      placeholder: "101"
    validations:
      required: false
  - type: input
    id: default_location_id
    attributes:
      label: Default Location ID
      description: The Hilti Location ID that newly created Assets will be created in
      placeholder: "1234567"
    validations:
      required: false
  - type: input
    id: default_location_manager_id
    attributes:
      label: Location Manager ID
      description: The Hilti Worker ID for the location manager that newly created Locations will be set to
      placeholder: "7654321"
    validations:
      required: false
  - type: input
    id: responsible_employee_id
    attributes:
      label: Responsible Employee ID
      description: The Hilti Worker ID for the responsible employee that newly created Assets will be assigned to
      placeholder: "5555555"
    validations:
      required: false
  - type: input
    id: inventory_employee_id
    attributes:
      label: Inventory Employee ID
      description: The Hilti Worker ID for the Inventory Employee that will be assigned to newly created Locations
      placeholder: "7777777"
    validations:
      required: false
  - type: dropdown
    attributes:
      label: ON!Track Assets -> Vista Equipment - CREATE
      description: Will this workflow be enabled for this customer?
      multiple: false
      options:
        - Enabled
        - Disabled
      default: 1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: ON!Track Transfers -> Vista Location Transfers - CREATE
      description: Will this workflow be enabled for this customer?
      multiple: false
      options:
        - Enabled
        - Disabled
      default: 1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Vista Employees -> ON!Track Workers - CREATE / UPDATE
      description: Will this workflow be enabled for this customer?
      multiple: false
      options:
        - Enabled
        - Disabled
      default: 1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Vista Equipment -> ON!Track Assets - CREATE / UPDATE
      description: Will this workflow be enabled for this customer?
      multiple: false
      options:
        - Enabled
        - Disabled
      default: 1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Vista Jobs -> ON!Track Locations - CREATE / UPDATE
      description: Will this workflow be enabled for this customer?
      multiple: false
      options:
        - Enabled
        - Disabled
      default: 1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Vista Locations -> ON!Track Locations - CREATE / UPDATE
      description: Will this workflow be enabled for this customer?
      multiple: false
      options:
        - Enabled
        - Disabled
      default: 1
    validations:
      required: true
  - type: markdown
    attributes:
      value: "This section is reserved for status tracking - only mark steps completed prior to ticket creation"
  - type: checkboxes
    attributes:
      label: Task List
      description: Indicate what steps have been completed
      options:
        - label: Initial Customer onboarding conversation
          required: false
        - label: Customer Configuration Details captured
          required: false
        - label: Customer ON!Track credentials transferred and verified 
          required: false
        - label: Data Review and transferred to Customer
          required: false
        - label: Data Reconciliation Complete
          required: false
        - label: Workflows configured and verified
          required: false
        - label: Workflows Activated
          required: false
        - label: Follow-Up discussion with customer completed
          required: false
